// Code generated by "stringer -type=ClientType -trimprefix=Cli"; DO NOT EDIT.

package grabbit

import "testing"

func TestClientType_String(t *testing.T) {
	tests := []struct {
		name string
		i    ClientType
		want string
	}{
		{"CliConnection", CliConnection, "Connection"},
		{"CliChannel", CliChannel, "Channel"},
		//----------------
		{ "out-of-bound-lower", CliConnection - 1, "ClientType(-1)" },
		{ "out-of-bound-upper", CliChannel + 1, "ClientType(2)" },
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.i.String(); got != tt.want {
				t.Errorf("ClientType.String() = %v, want %v", got, tt.want)
			}
		})
	}
}
