// Code generated by "stringer -type=ConfirmationOutcome -linecomment"; DO NOT EDIT.

package grabbit

import "testing"

func TestConfirmationOutcome_String(t *testing.T) {
	tests := []struct {
		name string
		i    ConfirmationOutcome
		want string
	}{
		{ "ConfirmationTimeOut", ConfirmationTimeOut, "no timely response" },
		{ "ConfirmationClosed", ConfirmationClosed, "data confirmation channel is closed" },
		{ "ConfirmationDisabled", ConfirmationDisabled, "base channel has not been put into confirm mode" },
		{ "ConfirmationPrevious", ConfirmationPrevious, "lower sequence number than expected" },
		{ "ConfirmationACK", ConfirmationACK, "ACK (publish confirmed)" },
		{ "ConfirmationNAK", ConfirmationNAK, "NAK (publish negative acknowledgement)" },
		//----------------
		{ "out-of-bound-lower", ConfirmationTimeOut - 1, "ConfirmationOutcome(-1)" },
		{ "out-of-bound-upper", ConfirmationNAK + 1, "ConfirmationOutcome(6)" },

	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.i.String(); got != tt.want {
				t.Errorf("ConfirmationOutcome.String() = %v, want %v", got, tt.want)
			}
		})
	}
}
