// Code generated by "stringer -type=EventType -trimprefix=Event"; DO NOT EDIT.

package grabbit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventUp-0]
	_ = x[EventDown-1]
	_ = x[EventCannotRecoverYet-2]
	_ = x[EventBlocked-3]
	_ = x[EventClosed-4]
}

const _EventType_name = "UpDownCannotRecoverYetBlockedClosed"

var _EventType_index = [...]uint8{0, 2, 6, 22, 29, 35}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
