// Code generated by "stringer -type=ConfirmationOutcome -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfirmationTimeOut-0]
	_ = x[ConfirmationClosed-1]
	_ = x[ConfirmationACK-2]
	_ = x[ConfirmationNAK-3]
}

const _ConfirmationOutcome_name = "no timely responsedata channel is closedpublish confirmed by serverpublish negative acknowledgement"

var _ConfirmationOutcome_index = [...]uint8{0, 18, 40, 67, 99}

func (i ConfirmationOutcome) String() string {
	if i < 0 || i >= ConfirmationOutcome(len(_ConfirmationOutcome_index)-1) {
		return "ConfirmationOutcome(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConfirmationOutcome_name[_ConfirmationOutcome_index[i]:_ConfirmationOutcome_index[i+1]]
}
