name: Test aand coverage
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: oldstable
          cache: true
      - name: Tests
        run: go test -race -v ./...
      - name: Coverage report
        uses: ncruces/go-coverage-report@v0.3.0
        with:
          amend: true
        continue-on-error: true
