name: Test and Coverage
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  test_coverage:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: oldstable
          cache: true
      - name: Test
        run: go test -tags test_env -coverprofile coverage.out -v
        if: |
          github.event_name == 'push' &&
          matrix.os == 'ubuntu-slim'
      - name: Coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          amend: true
          coverage-file: coverage.out
        continue-on-error: true
        if: |
          github.event_name == 'push' &&
          matrix.os == 'ubuntu-slim'
